name: Linux C

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: 3_Implementation/make
    - name: make run
      run: 3_Implementation/make run
 
